export default {
  SET_TO_STORE: 'SET_TO_STORE',
  CHANGE_TITLE: 'CHANGE_TITLE',

  CHANGE_ACTIVE_TAB: 'CHANGE_ACTIVE_TAB',
  DEFAULT_DESCRIPTION: 'DEFAULT_DESCRIPTION',
  BIRD_POSITION: 'BIRD_POSITION',
}
